version: '3'
services:
  mfrestapi:
    build: .
    depends_on:
      - db
    links:
      - db:db
    networks:
      - mf
  db:
    image: postgres:alpine
    volumes:
      - /etc/timezone:/etc/timezone:ro
      - /etc/localtime:/etc/localtime:ro
      - /etc/crystalcastle/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - mf

networks:
  mf:
    driver: bridge
