spring:
  profiles: deoni
company: DeoniMSP
networkConfigPath: connection_deoni.json
chaincodeName: nutrisafe-chaincode
channelName: cheese
certPath: deoni_admin_cert.pem
privateKeyPath: deoni_private_key
databaseConfig:
  name: nutrisaferestdb
  driver: postgresql
  username: postgres
  password: GRm%m5cgTmw3S&kjxV
  host: //localhost
  port: 5432

---

spring:
  profiles: brangus
company: BrangusMSP
networkConfigPath: connection_brangus.json
chaincodeName: nutrisafe-chaincode
channelName: cheese
certPath: brangus_admin_cert.pem
privateKeyPath: brangus_private_key
databaseConfig:
  name: nutrisaferestdb
  driver: postgresql
  username: postgres
  password: GRm%m5cgTmw3S&kjxV
  host: //localhost
  port: 5432