spring:
  profiles: deoni
name: deoni-YAML
company: DeoniMSP
environment: deoni
defaultNetwork: cheese
networkConfigPath: connection_deoni.json
chaincodeName: nutrisafe-chaincode
channelName: cheese
certPath: deoni_admin_cert.pem
privateKeyPath: deoni_private_key
databaseConfig:
  username: postgres
  password: Blender123
  host: //localhost
  port: 5432

---

spring:
  profiles: brangus
name: brangus-YAML
company: BrangusMSP
environment: brangus
defaultNetwork: cheese
networkConfigPath: connection_brangus.json
chaincodeName: nutrisafe-chaincode
channelName: cheese
certPath: brangus_admin_cert.pem
privateKeyPath: brangus_private_key
databaseConfig:
  username: postgres
  password: Blender123
  host: //localhost
  port: 5432