spring:
  profiles: test

# Member Info
org: DeoniMSP
cert: admin_cert.pem
pk: private_key

# Network Info
network: connection.json
channel: cheese
chaincode: nutrisafe-chaincode

# Database Info
dbName: mfrestdb
dbDriver: postgresql
dbUser: postgres
dbPassword: GRm%m5cgTmw3S&kjxV
dbHost: localhost/////
dbPort: 5432