# Member Info
org: # your member name
cert: # your certificate
pk: # your private key

# Network Info
network: connection.json # absolute path to your connection.json
channel: trackandtrace # The channel that you want to interact with
chaincode: MF-Chain-Code # the chaincode name

# Database Info
dbName: mfrestdb # the name of your user database
dbDriver: postgresql # the database driver
dbUser: postgres # the name of a privileged database user
dbPassword: # the pass of this privileged database user
dbHost: localhost # the host adress of your user database.
dbPort: 5432 # the port of your user database
