# Member Info
org: DeoniMSP # your member name
cert: # your certificate 
pk: # your private key

# Network Info
network: basic-network # path to your connection.json
channel: trackandtrace # The channel that you want to interact with
chaincode: MFContract # the chaincode name (default for MetaHL Fabric is MFContract)

# Database Info
dbName: mfrestdb # the name of your user database
dbDriver: postgresql # the database driver
dbUser: postgres # the name of a privileged database user
dbPassword: GRm%m5cgTmw3S&kjxV # the pass of this privileged database user
dbHost: localhost/ # the host adress of your user database
dbPort: 5432 # the port of your user database